### ISSUE TITLE
Error with relocatable python on apple silicon in v27

### ISSUE THREAD

**Issue by dnikles** [grahampugh/erase-install#288]
**Describe the bug**
the script fails to run on apple silicon on version 27. Works as expected on version 26.2

**To Reproduce**
run `sudo /Library/Management/erase-install/erase-install.sh --os=12 --update` on an apple silicon machine
 
**Expected behavior**
don't crash

**Code/log output**
```
sudo /Library/Management/erase-install/erase-install.sh --os=12 --update

   [erase-install] v27.0 script execution started: Tue Sep 27 14:14:48 EDT 2022
   [erase-install] Caffeinating this script (pid=72708)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] Installer found at /Applications/Install macOS Monterey.app.
   [check_installer_is_valid] Checking validity of /Applications/Install macOS Monterey.app.
   [check_installer_is_valid] Mounting /Applications/Install macOS Monterey.app/Contents/SharedSupport/SharedSupport.dmg
   [check_installer_is_valid] Using Build value from com_apple_MobileAsset_MacSoftwareUpdate.xml
Volume Shared Support on disk4s2 force-unmounted
   [compare_build_versions] Comparing (1) 21G115 with (2) 21G115
   [compare_build_versions] 21G115 = 21G115
   [check_installer_is_valid] Installer: 21G115 >= System: 21G115 : valid build.
   [erase-install] Checking for newer installer
   [check_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [check_python] Relocatable Python is installed in /Library/Management/erase-install
Traceback (most recent call last):
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib.py", line 7, in <module>
    from ._lib import lib, ffi
ImportError: dlopen(/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so, 0x0002): tried: '/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 49, in <module>
    import xattr
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib_build.h'
   [check_newer_available] ERROR running installinstallmacos.py, cannot continue

   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1178: 72723 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$
```

**Environment (please complete the following information):**
 - OS version 12
 - erase-install version 27. Bug not present on 26

**Additional context**
It looks like `/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so` is x86_64 only

**Comment by grahampugh** [comment]
I could not reproduce this error, even in a fresh VM on Apple Silicon without Rosetta2. However, please try again with the latest v27.0 pre-release. Make sure you install one of the packages that includes python.

**Comment by dnikles** [comment]
Confirmed no longer seeing issue on the latest release

**Comment by dnikles** [comment]
While I no longer see the issue on apple silicon, I now see the issue on intel. The problem seems to be with the same file.
```
   [erase-install] v27.0 script execution started: Mon Oct  3 08:20:45 EDT 2022
   [erase-install] Caffeinating this script (pid=4073)
   [erase-install] Looking for existing installer app or pkg
   [find_existing_installer] No valid installer found.
   [erase-install] Existing installer does not match requested OS, so replacing...
   [overwrite_existing_installer] Overwrite option selected. Deleting existing version.
   [erase-install] Running on architecture i386
   [check_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
   [check_python] Relocatable Python is installed in /Library/Management/erase-install
   [run_installinstallmacos] Checking that selected OS 12 is available

   [run_installinstallmacos] This command is now being run:

   installinstallmacos.py --workdir /Library/Management/erase-install --ignore-cache --raw --os 12
Traceback (most recent call last):
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib.py", line 7, in <module>
    from ._lib import lib, ffi
ImportError: dlopen(/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so, 2): no suitable image found.  Did find:
	/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so: mach-o, but wrong architecture
	/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/_lib.abi3.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 49, in <module>
    import xattr
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Management/erase-install/Python.framework/Versions/3.10/lib/python3.10/site-packages/xattr/lib_build.h'
   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.


   [erase-install] attempting to terminate the 'caffeinate' process - Termination message indicates success
/Library/Management/erase-install/erase-install.sh: line 1046:  4088 Terminated: 15          /usr/bin/caffeinate -dimsu -w $$


   [finish] Script exit code: 1
```

**Comment by grahampugh** [comment]
Can replicate this. I guess the python distribution is not universal. Going to have to look into that one...

**Comment by grahampugh** [comment]
Can you try again now? I have hopefully fixed it.

**Comment by dnikles** [comment]
fixed in my testing
